// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/linehk/go-microservices-blogger/service/blog/rpc/model (interfaces: BlogUserInfoModel)
//
// Generated by this command:
//
//	mockgen -destination=./mock_blog_user_info_model.go -package=model -self_package=github.com/linehk/go-microservices-blogger/service/blog/rpc/model github.com/linehk/go-microservices-blogger/service/blog/rpc/model BlogUserInfoModel
//

// Package model is a generated GoMock package.
package model

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBlogUserInfoModel is a mock of BlogUserInfoModel interface.
type MockBlogUserInfoModel struct {
	ctrl     *gomock.Controller
	recorder *MockBlogUserInfoModelMockRecorder
}

// MockBlogUserInfoModelMockRecorder is the mock recorder for MockBlogUserInfoModel.
type MockBlogUserInfoModelMockRecorder struct {
	mock *MockBlogUserInfoModel
}

// NewMockBlogUserInfoModel creates a new mock instance.
func NewMockBlogUserInfoModel(ctrl *gomock.Controller) *MockBlogUserInfoModel {
	mock := &MockBlogUserInfoModel{ctrl: ctrl}
	mock.recorder = &MockBlogUserInfoModelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlogUserInfoModel) EXPECT() *MockBlogUserInfoModelMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockBlogUserInfoModel) Delete(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBlogUserInfoModelMockRecorder) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBlogUserInfoModel)(nil).Delete), arg0, arg1)
}

// FindOne mocks base method.
func (m *MockBlogUserInfoModel) FindOne(arg0 context.Context, arg1 int64) (*BlogUserInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", arg0, arg1)
	ret0, _ := ret[0].(*BlogUserInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockBlogUserInfoModelMockRecorder) FindOne(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockBlogUserInfoModel)(nil).FindOne), arg0, arg1)
}

// FindOneByBlogUuid mocks base method.
func (m *MockBlogUserInfoModel) FindOneByBlogUuid(arg0 context.Context, arg1 string) (*BlogUserInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneByBlogUuid", arg0, arg1)
	ret0, _ := ret[0].(*BlogUserInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneByBlogUuid indicates an expected call of FindOneByBlogUuid.
func (mr *MockBlogUserInfoModelMockRecorder) FindOneByBlogUuid(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneByBlogUuid", reflect.TypeOf((*MockBlogUserInfoModel)(nil).FindOneByBlogUuid), arg0, arg1)
}

// FindOneByUserUuid mocks base method.
func (m *MockBlogUserInfoModel) FindOneByUserUuid(arg0 context.Context, arg1 string) (*BlogUserInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneByUserUuid", arg0, arg1)
	ret0, _ := ret[0].(*BlogUserInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneByUserUuid indicates an expected call of FindOneByUserUuid.
func (mr *MockBlogUserInfoModelMockRecorder) FindOneByUserUuid(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneByUserUuid", reflect.TypeOf((*MockBlogUserInfoModel)(nil).FindOneByUserUuid), arg0, arg1)
}

// FindOneByUserUuidAndBlogUuid mocks base method.
func (m *MockBlogUserInfoModel) FindOneByUserUuidAndBlogUuid(arg0 context.Context, arg1, arg2 string) (*BlogUserInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneByUserUuidAndBlogUuid", arg0, arg1, arg2)
	ret0, _ := ret[0].(*BlogUserInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneByUserUuidAndBlogUuid indicates an expected call of FindOneByUserUuidAndBlogUuid.
func (mr *MockBlogUserInfoModelMockRecorder) FindOneByUserUuidAndBlogUuid(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneByUserUuidAndBlogUuid", reflect.TypeOf((*MockBlogUserInfoModel)(nil).FindOneByUserUuidAndBlogUuid), arg0, arg1, arg2)
}

// FindOneByUuid mocks base method.
func (m *MockBlogUserInfoModel) FindOneByUuid(arg0 context.Context, arg1 string) (*BlogUserInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneByUuid", arg0, arg1)
	ret0, _ := ret[0].(*BlogUserInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneByUuid indicates an expected call of FindOneByUuid.
func (mr *MockBlogUserInfoModelMockRecorder) FindOneByUuid(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneByUuid", reflect.TypeOf((*MockBlogUserInfoModel)(nil).FindOneByUuid), arg0, arg1)
}

// Insert mocks base method.
func (m *MockBlogUserInfoModel) Insert(arg0 context.Context, arg1 *BlogUserInfo) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", arg0, arg1)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockBlogUserInfoModelMockRecorder) Insert(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockBlogUserInfoModel)(nil).Insert), arg0, arg1)
}

// Update mocks base method.
func (m *MockBlogUserInfoModel) Update(arg0 context.Context, arg1 *BlogUserInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockBlogUserInfoModelMockRecorder) Update(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockBlogUserInfoModel)(nil).Update), arg0, arg1)
}
