// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"github.com/linehk/go-blogger/service/user/rpc/internal/logic"
	"github.com/linehk/go-blogger/service/user/rpc/internal/svc"
	"github.com/linehk/go-blogger/service/user/rpc/user"
)

type UserServiceServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServiceServer
}

func NewUserServiceServer(svcCtx *svc.ServiceContext) *UserServiceServer {
	return &UserServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServiceServer) Get(ctx context.Context, in *user.GetReq) (*user.User, error) {
	l := logic.NewGetLogic(ctx, s.svcCtx)
	return l.Get(in)
}
