// Code generated by goctl. DO NOT EDIT.
package types

type CreateUserRequest struct {
	Username string `form:"username"`
	Password string `form:"password"`
	Email    string `form:"email"`
}

type EmptyRequest struct {
}

type EmptyResponse struct {
}
