// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package userservice

import (
	"context"

	"github.com/linehk/go-blogger/service/user/rpc/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Blogs  = user.Blogs
	GetReq = user.GetReq
	Locale = user.Locale
	User   = user.User

	UserService interface {
		Get(ctx context.Context, in *GetReq, opts ...grpc.CallOption) (*User, error)
	}

	defaultUserService struct {
		cli zrpc.Client
	}
)

func NewUserService(cli zrpc.Client) UserService {
	return &defaultUserService{
		cli: cli,
	}
}

func (m *defaultUserService) Get(ctx context.Context, in *GetReq, opts ...grpc.CallOption) (*User, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.Get(ctx, in, opts...)
}
