// Code generated by goctl. DO NOT EDIT.
// Source: user_center.proto

package usercenterclient

import (
	"context"

	"github.com/linehk/go-blogger/service/user_center/rpc/user_center"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateUserRequest = user_center.CreateUserRequest
	EmptyRequest      = user_center.EmptyRequest
	EmptyResponse     = user_center.EmptyResponse

	UserCenter interface {
		CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	}

	defaultUserCenter struct {
		cli zrpc.Client
	}
)

func NewUserCenter(cli zrpc.Client) UserCenter {
	return &defaultUserCenter{
		cli: cli,
	}
}

func (m *defaultUserCenter) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	client := user_center.NewUserCenterClient(m.cli.Conn())
	return client.CreateUser(ctx, in, opts...)
}
