// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: service/blog/rpc/blog.proto

package blog

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Blog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind           string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Id             string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Published      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=published,proto3" json:"published,omitempty"`
	Updated        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated,proto3" json:"updated,omitempty"`
	Url            string                 `protobuf:"bytes,7,opt,name=url,proto3" json:"url,omitempty"`
	SelfLink       string                 `protobuf:"bytes,8,opt,name=selfLink,proto3" json:"selfLink,omitempty"`
	Posts          []*Posts               `protobuf:"bytes,9,rep,name=posts,proto3" json:"posts,omitempty"`
	Pages          []*Pages               `protobuf:"bytes,10,rep,name=pages,proto3" json:"pages,omitempty"`
	CustomMetaData string                 `protobuf:"bytes,11,opt,name=customMetaData,proto3" json:"customMetaData,omitempty"`
}

func (x *Blog) Reset() {
	*x = Blog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_blog_rpc_blog_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Blog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blog) ProtoMessage() {}

func (x *Blog) ProtoReflect() protoreflect.Message {
	mi := &file_service_blog_rpc_blog_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blog.ProtoReflect.Descriptor instead.
func (*Blog) Descriptor() ([]byte, []int) {
	return file_service_blog_rpc_blog_proto_rawDescGZIP(), []int{0}
}

func (x *Blog) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Blog) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Blog) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Blog) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Blog) GetPublished() *timestamppb.Timestamp {
	if x != nil {
		return x.Published
	}
	return nil
}

func (x *Blog) GetUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.Updated
	}
	return nil
}

func (x *Blog) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Blog) GetSelfLink() string {
	if x != nil {
		return x.SelfLink
	}
	return ""
}

func (x *Blog) GetPosts() []*Posts {
	if x != nil {
		return x.Posts
	}
	return nil
}

func (x *Blog) GetPages() []*Pages {
	if x != nil {
		return x.Pages
	}
	return nil
}

func (x *Blog) GetCustomMetaData() string {
	if x != nil {
		return x.CustomMetaData
	}
	return ""
}

type Posts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalItems string `protobuf:"bytes,1,opt,name=totalItems,proto3" json:"totalItems,omitempty"`
	SelfLink   string `protobuf:"bytes,2,opt,name=selfLink,proto3" json:"selfLink,omitempty"`
}

func (x *Posts) Reset() {
	*x = Posts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_blog_rpc_blog_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Posts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Posts) ProtoMessage() {}

func (x *Posts) ProtoReflect() protoreflect.Message {
	mi := &file_service_blog_rpc_blog_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Posts.ProtoReflect.Descriptor instead.
func (*Posts) Descriptor() ([]byte, []int) {
	return file_service_blog_rpc_blog_proto_rawDescGZIP(), []int{1}
}

func (x *Posts) GetTotalItems() string {
	if x != nil {
		return x.TotalItems
	}
	return ""
}

func (x *Posts) GetSelfLink() string {
	if x != nil {
		return x.SelfLink
	}
	return ""
}

type Pages struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalItems string `protobuf:"bytes,1,opt,name=totalItems,proto3" json:"totalItems,omitempty"`
	SelfLink   string `protobuf:"bytes,2,opt,name=selfLink,proto3" json:"selfLink,omitempty"`
}

func (x *Pages) Reset() {
	*x = Pages{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_blog_rpc_blog_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pages) ProtoMessage() {}

func (x *Pages) ProtoReflect() protoreflect.Message {
	mi := &file_service_blog_rpc_blog_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pages.ProtoReflect.Descriptor instead.
func (*Pages) Descriptor() ([]byte, []int) {
	return file_service_blog_rpc_blog_proto_rawDescGZIP(), []int{2}
}

func (x *Pages) GetTotalItems() string {
	if x != nil {
		return x.TotalItems
	}
	return ""
}

func (x *Pages) GetSelfLink() string {
	if x != nil {
		return x.SelfLink
	}
	return ""
}

type GetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlogId   string `protobuf:"bytes,1,opt,name=blogId,proto3" json:"blogId,omitempty"`
	MaxPosts uint64 `protobuf:"varint,2,opt,name=maxPosts,proto3" json:"maxPosts,omitempty"`
}

func (x *GetReq) Reset() {
	*x = GetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_blog_rpc_blog_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReq) ProtoMessage() {}

func (x *GetReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_blog_rpc_blog_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReq.ProtoReflect.Descriptor instead.
func (*GetReq) Descriptor() ([]byte, []int) {
	return file_service_blog_rpc_blog_proto_rawDescGZIP(), []int{3}
}

func (x *GetReq) GetBlogId() string {
	if x != nil {
		return x.BlogId
	}
	return ""
}

func (x *GetReq) GetMaxPosts() uint64 {
	if x != nil {
		return x.MaxPosts
	}
	return 0
}

type GetByUrlReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *GetByUrlReq) Reset() {
	*x = GetByUrlReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_blog_rpc_blog_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetByUrlReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByUrlReq) ProtoMessage() {}

func (x *GetByUrlReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_blog_rpc_blog_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByUrlReq.ProtoReflect.Descriptor instead.
func (*GetByUrlReq) Descriptor() ([]byte, []int) {
	return file_service_blog_rpc_blog_proto_rawDescGZIP(), []int{4}
}

func (x *GetByUrlReq) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ListByUserReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId        string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	FetchUserInfo bool   `protobuf:"varint,2,opt,name=fetchUserInfo,proto3" json:"fetchUserInfo,omitempty"`
	View          string `protobuf:"bytes,3,opt,name=view,proto3" json:"view,omitempty"`
}

func (x *ListByUserReq) Reset() {
	*x = ListByUserReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_blog_rpc_blog_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListByUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListByUserReq) ProtoMessage() {}

func (x *ListByUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_blog_rpc_blog_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListByUserReq.ProtoReflect.Descriptor instead.
func (*ListByUserReq) Descriptor() ([]byte, []int) {
	return file_service_blog_rpc_blog_proto_rawDescGZIP(), []int{5}
}

func (x *ListByUserReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListByUserReq) GetFetchUserInfo() bool {
	if x != nil {
		return x.FetchUserInfo
	}
	return false
}

func (x *ListByUserReq) GetView() string {
	if x != nil {
		return x.View
	}
	return ""
}

type ListByUserResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind          string           `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Items         []*Blog          `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	BlogUserInfos []*BlogUserInfos `protobuf:"bytes,3,rep,name=blogUserInfos,proto3" json:"blogUserInfos,omitempty"`
}

func (x *ListByUserResp) Reset() {
	*x = ListByUserResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_blog_rpc_blog_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListByUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListByUserResp) ProtoMessage() {}

func (x *ListByUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_service_blog_rpc_blog_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListByUserResp.ProtoReflect.Descriptor instead.
func (*ListByUserResp) Descriptor() ([]byte, []int) {
	return file_service_blog_rpc_blog_proto_rawDescGZIP(), []int{6}
}

func (x *ListByUserResp) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ListByUserResp) GetItems() []*Blog {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListByUserResp) GetBlogUserInfos() []*BlogUserInfos {
	if x != nil {
		return x.BlogUserInfos
	}
	return nil
}

type BlogUserInfos struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind         string        `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Blog         *Blog         `protobuf:"bytes,2,opt,name=blog,proto3" json:"blog,omitempty"`
	BlogUserInfo *BlogUserInfo `protobuf:"bytes,3,opt,name=blog_user_info,json=blogUserInfo,proto3" json:"blog_user_info,omitempty"`
}

func (x *BlogUserInfos) Reset() {
	*x = BlogUserInfos{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_blog_rpc_blog_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlogUserInfos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlogUserInfos) ProtoMessage() {}

func (x *BlogUserInfos) ProtoReflect() protoreflect.Message {
	mi := &file_service_blog_rpc_blog_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlogUserInfos.ProtoReflect.Descriptor instead.
func (*BlogUserInfos) Descriptor() ([]byte, []int) {
	return file_service_blog_rpc_blog_proto_rawDescGZIP(), []int{7}
}

func (x *BlogUserInfos) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *BlogUserInfos) GetBlog() *Blog {
	if x != nil {
		return x.Blog
	}
	return nil
}

func (x *BlogUserInfos) GetBlogUserInfo() *BlogUserInfo {
	if x != nil {
		return x.BlogUserInfo
	}
	return nil
}

type BlogUserInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind           string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	UserId         string `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	BlogId         string `protobuf:"bytes,3,opt,name=blogId,proto3" json:"blogId,omitempty"`
	PhotosAlbumKey string `protobuf:"bytes,4,opt,name=photosAlbumKey,proto3" json:"photosAlbumKey,omitempty"`
	HasAdminAccess bool   `protobuf:"varint,5,opt,name=hasAdminAccess,proto3" json:"hasAdminAccess,omitempty"`
}

func (x *BlogUserInfo) Reset() {
	*x = BlogUserInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_blog_rpc_blog_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlogUserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlogUserInfo) ProtoMessage() {}

func (x *BlogUserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_service_blog_rpc_blog_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlogUserInfo.ProtoReflect.Descriptor instead.
func (*BlogUserInfo) Descriptor() ([]byte, []int) {
	return file_service_blog_rpc_blog_proto_rawDescGZIP(), []int{8}
}

func (x *BlogUserInfo) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *BlogUserInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BlogUserInfo) GetBlogId() string {
	if x != nil {
		return x.BlogId
	}
	return ""
}

func (x *BlogUserInfo) GetPhotosAlbumKey() string {
	if x != nil {
		return x.PhotosAlbumKey
	}
	return ""
}

func (x *BlogUserInfo) GetHasAdminAccess() bool {
	if x != nil {
		return x.HasAdminAccess
	}
	return false
}

type BlogUserInfosReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlogId   string `protobuf:"bytes,1,opt,name=blogId,proto3" json:"blogId,omitempty"`
	UserId   string `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	MaxPosts uint64 `protobuf:"varint,3,opt,name=maxPosts,proto3" json:"maxPosts,omitempty"`
}

func (x *BlogUserInfosReq) Reset() {
	*x = BlogUserInfosReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_blog_rpc_blog_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlogUserInfosReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlogUserInfosReq) ProtoMessage() {}

func (x *BlogUserInfosReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_blog_rpc_blog_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlogUserInfosReq.ProtoReflect.Descriptor instead.
func (*BlogUserInfosReq) Descriptor() ([]byte, []int) {
	return file_service_blog_rpc_blog_proto_rawDescGZIP(), []int{9}
}

func (x *BlogUserInfosReq) GetBlogId() string {
	if x != nil {
		return x.BlogId
	}
	return ""
}

func (x *BlogUserInfosReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BlogUserInfosReq) GetMaxPosts() uint64 {
	if x != nil {
		return x.MaxPosts
	}
	return 0
}

type PageViews struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind   string   `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	BlogId int64    `protobuf:"varint,2,opt,name=blogId,proto3" json:"blogId,omitempty"`
	Counts []*Count `protobuf:"bytes,3,rep,name=counts,proto3" json:"counts,omitempty"`
}

func (x *PageViews) Reset() {
	*x = PageViews{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_blog_rpc_blog_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageViews) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageViews) ProtoMessage() {}

func (x *PageViews) ProtoReflect() protoreflect.Message {
	mi := &file_service_blog_rpc_blog_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageViews.ProtoReflect.Descriptor instead.
func (*PageViews) Descriptor() ([]byte, []int) {
	return file_service_blog_rpc_blog_proto_rawDescGZIP(), []int{10}
}

func (x *PageViews) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *PageViews) GetBlogId() int64 {
	if x != nil {
		return x.BlogId
	}
	return 0
}

func (x *PageViews) GetCounts() []*Count {
	if x != nil {
		return x.Counts
	}
	return nil
}

type Count struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimeRange string `protobuf:"bytes,1,opt,name=timeRange,proto3" json:"timeRange,omitempty"`
	Count     uint64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *Count) Reset() {
	*x = Count{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_blog_rpc_blog_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Count) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Count) ProtoMessage() {}

func (x *Count) ProtoReflect() protoreflect.Message {
	mi := &file_service_blog_rpc_blog_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Count.ProtoReflect.Descriptor instead.
func (*Count) Descriptor() ([]byte, []int) {
	return file_service_blog_rpc_blog_proto_rawDescGZIP(), []int{11}
}

func (x *Count) GetTimeRange() string {
	if x != nil {
		return x.TimeRange
	}
	return ""
}

func (x *Count) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetPageViewsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlogId string `protobuf:"bytes,1,opt,name=blogId,proto3" json:"blogId,omitempty"`
	Range  string `protobuf:"bytes,2,opt,name=range,proto3" json:"range,omitempty"`
}

func (x *GetPageViewsReq) Reset() {
	*x = GetPageViewsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_blog_rpc_blog_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPageViewsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPageViewsReq) ProtoMessage() {}

func (x *GetPageViewsReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_blog_rpc_blog_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPageViewsReq.ProtoReflect.Descriptor instead.
func (*GetPageViewsReq) Descriptor() ([]byte, []int) {
	return file_service_blog_rpc_blog_proto_rawDescGZIP(), []int{12}
}

func (x *GetPageViewsReq) GetBlogId() string {
	if x != nil {
		return x.BlogId
	}
	return ""
}

func (x *GetPageViewsReq) GetRange() string {
	if x != nil {
		return x.Range
	}
	return ""
}

var File_service_blog_rpc_blog_proto protoreflect.FileDescriptor

var file_service_blog_rpc_blog_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x62, 0x6c, 0x6f, 0x67, 0x2f, 0x72,
	0x70, 0x63, 0x2f, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x62,
	0x6c, 0x6f, 0x67, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xec, 0x02, 0x0a, 0x04, 0x42, 0x6c, 0x6f, 0x67, 0x12, 0x12, 0x0a,
	0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e,
	0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x38, 0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x73, 0x68, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65,
	0x64, 0x12, 0x34, 0x0a, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x07,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6c,
	0x66, 0x4c, 0x69, 0x6e, 0x6b, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6c,
	0x66, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x21, 0x0a, 0x05, 0x70, 0x6f, 0x73, 0x74, 0x73, 0x18, 0x09,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x50, 0x6f, 0x73, 0x74,
	0x73, 0x52, 0x05, 0x70, 0x6f, 0x73, 0x74, 0x73, 0x12, 0x21, 0x0a, 0x05, 0x70, 0x61, 0x67, 0x65,
	0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x50,
	0x61, 0x67, 0x65, 0x73, 0x52, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x12, 0x26, 0x0a, 0x0e, 0x63,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x4d, 0x65, 0x74, 0x61, 0x44,
	0x61, 0x74, 0x61, 0x22, 0x43, 0x0a, 0x05, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x12, 0x1e, 0x0a, 0x0a,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x1a, 0x0a, 0x08,
	0x73, 0x65, 0x6c, 0x66, 0x4c, 0x69, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x73, 0x65, 0x6c, 0x66, 0x4c, 0x69, 0x6e, 0x6b, 0x22, 0x43, 0x0a, 0x05, 0x50, 0x61, 0x67, 0x65,
	0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x49, 0x74, 0x65, 0x6d,
	0x73, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6c, 0x66, 0x4c, 0x69, 0x6e, 0x6b, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6c, 0x66, 0x4c, 0x69, 0x6e, 0x6b, 0x22, 0x3c, 0x0a,
	0x06, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x6c, 0x6f, 0x67, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x6c, 0x6f, 0x67, 0x49, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x6d, 0x61, 0x78, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x08, 0x6d, 0x61, 0x78, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x22, 0x1f, 0x0a, 0x0b, 0x47,
	0x65, 0x74, 0x42, 0x79, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x61, 0x0a, 0x0d,
	0x4c, 0x69, 0x73, 0x74, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x66, 0x65, 0x74, 0x63, 0x68, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x66, 0x65,
	0x74, 0x63, 0x68, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x76,
	0x69, 0x65, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x76, 0x69, 0x65, 0x77, 0x22,
	0x81, 0x01, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x20, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x42, 0x6c, 0x6f,
	0x67, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x39, 0x0a, 0x0d, 0x62, 0x6c, 0x6f, 0x67,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x73, 0x52, 0x0d, 0x62, 0x6c, 0x6f, 0x67, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x73, 0x22, 0x7d, 0x0a, 0x0d, 0x42, 0x6c, 0x6f, 0x67, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x1e, 0x0a, 0x04, 0x62, 0x6c, 0x6f, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x42, 0x6c,
	0x6f, 0x67, 0x52, 0x04, 0x62, 0x6c, 0x6f, 0x67, 0x12, 0x38, 0x0a, 0x0e, 0x62, 0x6c, 0x6f, 0x67,
	0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x62, 0x6c, 0x6f, 0x67, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x22, 0xa2, 0x01, 0x0a, 0x0c, 0x42, 0x6c, 0x6f, 0x67, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x62, 0x6c, 0x6f, 0x67, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x62, 0x6c, 0x6f, 0x67, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x70, 0x68, 0x6f, 0x74, 0x6f,
	0x73, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x4b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0e, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x73, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x4b, 0x65, 0x79, 0x12,
	0x26, 0x0a, 0x0e, 0x68, 0x61, 0x73, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x41, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x68, 0x61, 0x73, 0x41, 0x64, 0x6d, 0x69,
	0x6e, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x5e, 0x0a, 0x10, 0x42, 0x6c, 0x6f, 0x67, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x62,
	0x6c, 0x6f, 0x67, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x6c, 0x6f,
	0x67, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6d,
	0x61, 0x78, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x6d,
	0x61, 0x78, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x22, 0x5c, 0x0a, 0x09, 0x50, 0x61, 0x67, 0x65, 0x56,
	0x69, 0x65, 0x77, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x6c, 0x6f, 0x67,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x62, 0x6c, 0x6f, 0x67, 0x49, 0x64,
	0x12, 0x23, 0x0a, 0x06, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x06, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x73, 0x22, 0x3b, 0x0a, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x22, 0x3f, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x50, 0x61, 0x67, 0x65, 0x56, 0x69, 0x65,
	0x77, 0x73, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x6c, 0x6f, 0x67, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x6c, 0x6f, 0x67, 0x49, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x61,
	0x6e, 0x67, 0x65, 0x32, 0x8b, 0x02, 0x0a, 0x0b, 0x42, 0x6c, 0x6f, 0x67, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x1f, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x0c, 0x2e, 0x62, 0x6c, 0x6f,
	0x67, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x0a, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x2e,
	0x42, 0x6c, 0x6f, 0x67, 0x12, 0x29, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x42, 0x79, 0x55, 0x72, 0x6c,
	0x12, 0x11, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x79, 0x55, 0x72, 0x6c,
	0x52, 0x65, 0x71, 0x1a, 0x0a, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x12,
	0x37, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x12, 0x13, 0x2e,
	0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x1a, 0x14, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x79,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3f, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x42,
	0x6c, 0x6f, 0x67, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x12, 0x16, 0x2e, 0x62,
	0x6c, 0x6f, 0x67, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x73, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x42, 0x6c, 0x6f, 0x67,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x12, 0x36, 0x0a, 0x0c, 0x47, 0x65, 0x74,
	0x50, 0x61, 0x67, 0x65, 0x56, 0x69, 0x65, 0x77, 0x73, 0x12, 0x15, 0x2e, 0x62, 0x6c, 0x6f, 0x67,
	0x2e, 0x47, 0x65, 0x74, 0x50, 0x61, 0x67, 0x65, 0x56, 0x69, 0x65, 0x77, 0x73, 0x52, 0x65, 0x71,
	0x1a, 0x0f, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x56, 0x69, 0x65, 0x77,
	0x73, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x62, 0x6c, 0x6f, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_service_blog_rpc_blog_proto_rawDescOnce sync.Once
	file_service_blog_rpc_blog_proto_rawDescData = file_service_blog_rpc_blog_proto_rawDesc
)

func file_service_blog_rpc_blog_proto_rawDescGZIP() []byte {
	file_service_blog_rpc_blog_proto_rawDescOnce.Do(func() {
		file_service_blog_rpc_blog_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_blog_rpc_blog_proto_rawDescData)
	})
	return file_service_blog_rpc_blog_proto_rawDescData
}

var file_service_blog_rpc_blog_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_service_blog_rpc_blog_proto_goTypes = []interface{}{
	(*Blog)(nil),                  // 0: blog.Blog
	(*Posts)(nil),                 // 1: blog.Posts
	(*Pages)(nil),                 // 2: blog.Pages
	(*GetReq)(nil),                // 3: blog.GetReq
	(*GetByUrlReq)(nil),           // 4: blog.GetByUrlReq
	(*ListByUserReq)(nil),         // 5: blog.ListByUserReq
	(*ListByUserResp)(nil),        // 6: blog.ListByUserResp
	(*BlogUserInfos)(nil),         // 7: blog.BlogUserInfos
	(*BlogUserInfo)(nil),          // 8: blog.BlogUserInfo
	(*BlogUserInfosReq)(nil),      // 9: blog.BlogUserInfosReq
	(*PageViews)(nil),             // 10: blog.PageViews
	(*Count)(nil),                 // 11: blog.Count
	(*GetPageViewsReq)(nil),       // 12: blog.GetPageViewsReq
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
}
var file_service_blog_rpc_blog_proto_depIdxs = []int32{
	13, // 0: blog.Blog.published:type_name -> google.protobuf.Timestamp
	13, // 1: blog.Blog.updated:type_name -> google.protobuf.Timestamp
	1,  // 2: blog.Blog.posts:type_name -> blog.Posts
	2,  // 3: blog.Blog.pages:type_name -> blog.Pages
	0,  // 4: blog.ListByUserResp.items:type_name -> blog.Blog
	7,  // 5: blog.ListByUserResp.blogUserInfos:type_name -> blog.BlogUserInfos
	0,  // 6: blog.BlogUserInfos.blog:type_name -> blog.Blog
	8,  // 7: blog.BlogUserInfos.blog_user_info:type_name -> blog.BlogUserInfo
	11, // 8: blog.PageViews.counts:type_name -> blog.Count
	3,  // 9: blog.BlogService.Get:input_type -> blog.GetReq
	4,  // 10: blog.BlogService.GetByUrl:input_type -> blog.GetByUrlReq
	5,  // 11: blog.BlogService.ListByUser:input_type -> blog.ListByUserReq
	9,  // 12: blog.BlogService.GetBlogUserInfos:input_type -> blog.BlogUserInfosReq
	12, // 13: blog.BlogService.GetPageViews:input_type -> blog.GetPageViewsReq
	0,  // 14: blog.BlogService.Get:output_type -> blog.Blog
	0,  // 15: blog.BlogService.GetByUrl:output_type -> blog.Blog
	6,  // 16: blog.BlogService.ListByUser:output_type -> blog.ListByUserResp
	7,  // 17: blog.BlogService.GetBlogUserInfos:output_type -> blog.BlogUserInfos
	10, // 18: blog.BlogService.GetPageViews:output_type -> blog.PageViews
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_service_blog_rpc_blog_proto_init() }
func file_service_blog_rpc_blog_proto_init() {
	if File_service_blog_rpc_blog_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_service_blog_rpc_blog_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Blog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_blog_rpc_blog_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Posts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_blog_rpc_blog_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pages); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_blog_rpc_blog_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_blog_rpc_blog_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetByUrlReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_blog_rpc_blog_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListByUserReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_blog_rpc_blog_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListByUserResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_blog_rpc_blog_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlogUserInfos); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_blog_rpc_blog_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlogUserInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_blog_rpc_blog_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlogUserInfosReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_blog_rpc_blog_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageViews); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_blog_rpc_blog_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Count); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_blog_rpc_blog_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPageViewsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_blog_rpc_blog_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_blog_rpc_blog_proto_goTypes,
		DependencyIndexes: file_service_blog_rpc_blog_proto_depIdxs,
		MessageInfos:      file_service_blog_rpc_blog_proto_msgTypes,
	}.Build()
	File_service_blog_rpc_blog_proto = out.File
	file_service_blog_rpc_blog_proto_rawDesc = nil
	file_service_blog_rpc_blog_proto_goTypes = nil
	file_service_blog_rpc_blog_proto_depIdxs = nil
}
