// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/linehk/go-microservices-blogger/service/user/rpc/model (interfaces: LocaleModel)
//
// Generated by this command:
//
//	mockgen -destination=./mock_locale_model.go -package=model -self_package=github.com/linehk/go-microservices-blogger/service/user/rpc/model github.com/linehk/go-microservices-blogger/service/user/rpc/model LocaleModel
//

// Package model is a generated GoMock package.
package model

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLocaleModel is a mock of LocaleModel interface.
type MockLocaleModel struct {
	ctrl     *gomock.Controller
	recorder *MockLocaleModelMockRecorder
}

// MockLocaleModelMockRecorder is the mock recorder for MockLocaleModel.
type MockLocaleModelMockRecorder struct {
	mock *MockLocaleModel
}

// NewMockLocaleModel creates a new mock instance.
func NewMockLocaleModel(ctrl *gomock.Controller) *MockLocaleModel {
	mock := &MockLocaleModel{ctrl: ctrl}
	mock.recorder = &MockLocaleModelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLocaleModel) EXPECT() *MockLocaleModelMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockLocaleModel) Delete(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockLocaleModelMockRecorder) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockLocaleModel)(nil).Delete), arg0, arg1)
}

// FindOne mocks base method.
func (m *MockLocaleModel) FindOne(arg0 context.Context, arg1 int64) (*Locale, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", arg0, arg1)
	ret0, _ := ret[0].(*Locale)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockLocaleModelMockRecorder) FindOne(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockLocaleModel)(nil).FindOne), arg0, arg1)
}

// FindOneByAppUserUuid mocks base method.
func (m *MockLocaleModel) FindOneByAppUserUuid(arg0 context.Context, arg1 string) (*Locale, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneByAppUserUuid", arg0, arg1)
	ret0, _ := ret[0].(*Locale)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneByAppUserUuid indicates an expected call of FindOneByAppUserUuid.
func (mr *MockLocaleModelMockRecorder) FindOneByAppUserUuid(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneByAppUserUuid", reflect.TypeOf((*MockLocaleModel)(nil).FindOneByAppUserUuid), arg0, arg1)
}

// FindOneByUuid mocks base method.
func (m *MockLocaleModel) FindOneByUuid(arg0 context.Context, arg1 string) (*Locale, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneByUuid", arg0, arg1)
	ret0, _ := ret[0].(*Locale)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneByUuid indicates an expected call of FindOneByUuid.
func (mr *MockLocaleModelMockRecorder) FindOneByUuid(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneByUuid", reflect.TypeOf((*MockLocaleModel)(nil).FindOneByUuid), arg0, arg1)
}

// Insert mocks base method.
func (m *MockLocaleModel) Insert(arg0 context.Context, arg1 *Locale) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", arg0, arg1)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockLocaleModelMockRecorder) Insert(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockLocaleModel)(nil).Insert), arg0, arg1)
}

// Update mocks base method.
func (m *MockLocaleModel) Update(arg0 context.Context, arg1 *Locale) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockLocaleModelMockRecorder) Update(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockLocaleModel)(nil).Update), arg0, arg1)
}
