// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/linehk/go-microservices-blogger/service/post/rpc/model (interfaces: LabelModel)
//
// Generated by this command:
//
//	mockgen -destination=./mock_label_model.go -package=model -self_package=github.com/linehk/go-microservices-blogger/service/post/rpc/model github.com/linehk/go-microservices-blogger/service/post/rpc/model LabelModel
//

// Package model is a generated GoMock package.
package model

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLabelModel is a mock of LabelModel interface.
type MockLabelModel struct {
	ctrl     *gomock.Controller
	recorder *MockLabelModelMockRecorder
}

// MockLabelModelMockRecorder is the mock recorder for MockLabelModel.
type MockLabelModelMockRecorder struct {
	mock *MockLabelModel
}

// NewMockLabelModel creates a new mock instance.
func NewMockLabelModel(ctrl *gomock.Controller) *MockLabelModel {
	mock := &MockLabelModel{ctrl: ctrl}
	mock.recorder = &MockLabelModelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLabelModel) EXPECT() *MockLabelModelMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockLabelModel) Delete(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockLabelModelMockRecorder) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockLabelModel)(nil).Delete), arg0, arg1)
}

// FindOne mocks base method.
func (m *MockLabelModel) FindOne(arg0 context.Context, arg1 int64) (*Label, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", arg0, arg1)
	ret0, _ := ret[0].(*Label)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockLabelModelMockRecorder) FindOne(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockLabelModel)(nil).FindOne), arg0, arg1)
}

// FindOneByPostUuid mocks base method.
func (m *MockLabelModel) FindOneByPostUuid(arg0 context.Context, arg1 string) (*Label, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneByPostUuid", arg0, arg1)
	ret0, _ := ret[0].(*Label)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneByPostUuid indicates an expected call of FindOneByPostUuid.
func (mr *MockLabelModelMockRecorder) FindOneByPostUuid(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneByPostUuid", reflect.TypeOf((*MockLabelModel)(nil).FindOneByPostUuid), arg0, arg1)
}

// FindOneByUuid mocks base method.
func (m *MockLabelModel) FindOneByUuid(arg0 context.Context, arg1 string) (*Label, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneByUuid", arg0, arg1)
	ret0, _ := ret[0].(*Label)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneByUuid indicates an expected call of FindOneByUuid.
func (mr *MockLabelModelMockRecorder) FindOneByUuid(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneByUuid", reflect.TypeOf((*MockLabelModel)(nil).FindOneByUuid), arg0, arg1)
}

// Insert mocks base method.
func (m *MockLabelModel) Insert(arg0 context.Context, arg1 *Label) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", arg0, arg1)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockLabelModelMockRecorder) Insert(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockLabelModel)(nil).Insert), arg0, arg1)
}

// ListByPostUuid mocks base method.
func (m *MockLabelModel) ListByPostUuid(arg0 context.Context, arg1 string) ([]*Label, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByPostUuid", arg0, arg1)
	ret0, _ := ret[0].([]*Label)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByPostUuid indicates an expected call of ListByPostUuid.
func (mr *MockLabelModelMockRecorder) ListByPostUuid(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByPostUuid", reflect.TypeOf((*MockLabelModel)(nil).ListByPostUuid), arg0, arg1)
}

// Update mocks base method.
func (m *MockLabelModel) Update(arg0 context.Context, arg1 *Label) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockLabelModelMockRecorder) Update(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockLabelModel)(nil).Update), arg0, arg1)
}
