// Code generated by goctl. DO NOT EDIT.
// Source: user_center.proto

package server

import (
	"context"

	"github.com/linehk/go-blogger/service/user_center/rpc/internal/logic"
	"github.com/linehk/go-blogger/service/user_center/rpc/internal/svc"
	"github.com/linehk/go-blogger/service/user_center/rpc/user_center"
)

type UserCenterServer struct {
	svcCtx *svc.ServiceContext
	user_center.UnimplementedUserCenterServer
}

func NewUserCenterServer(svcCtx *svc.ServiceContext) *UserCenterServer {
	return &UserCenterServer{
		svcCtx: svcCtx,
	}
}

func (s *UserCenterServer) Ping(ctx context.Context, in *user_center.Request) (*user_center.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
